# Generated by Django 3.1.6 on 2021-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('cowsay_type', models.CharField(choices=[('Default', 'Default'), ('Tux', 'Tux'), ('Dragon', 'Dragon'), ('Kitty', 'Kitty'), ('Skeleton', 'Skeleton')], max_length=11)),
            ],
        ),
    ]
