# Generated by Django 3.1.6 on 2021-02-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_auto_20210211_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
