# Generated by Django 3.1.6 on 2021-02-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0003_postnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostNew',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(),
        ),
    ]
