# Generated by Django 3.1.6 on 2021-02-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0004_auto_20210212_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
